name: astronomy_pictures
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^5.0.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true